version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    container_name: my_cache
    ports:
      - '6379:6379' 
    command: redis-server --save 20 1 --loglevel warning --requirepass changeme
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - cache:/data
    networks:
      - backend
volumes:
  cache:
    driver: local
networks:
  backend:
    driver: bridge

